name: Label PRs
on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  check-changes: 
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.check-paths-step.outputs.backend }}
      graphql-schema: ${{ steps.check-paths-step.outputs.graphql-schema }}
      ios: ${{ steps.check-paths-step.outputs.ios }}
      web: ${{ steps.check-paths-step.outputs.web }}
    steps:
      - id: check-paths-step
        uses: ky1ejs/check-diff-paths-action@v0.2.0
        with:
          paths: |-
            {
              "backend": "^backend\\\/.*",
              "graphql-schema": "backend\\\/graphql\\\/schema\\.graphql",
              "ios": "ios\\\/.*",
              "web": "web\\\/.*"
            }
          github-token: ${{ secrets.GITHUB_TOKEN }}
  label_issues:
    runs-on: ubuntu-latest
    needs: check-changes
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_REPO: ${{ github.repository }}
      NUMBER: ${{ github.event.pull_request.number }}
    permissions:
      pull-requests: write
    steps:
      - run: gh issue edit "$NUMBER" --add-label "backend"
        if: ${{ needs.check-changes.outputs.backend == 'true' }}
      - run: gh issue edit "$NUMBER" --remove-label "backend"
        if: ${{ needs.check-changes.outputs.backend == 'false' }}
      
      - run: gh issue edit "$NUMBER" --add-label "graphql-schema"
        if: ${{ needs.check-changes.outputs.graphql-schema == 'true' }}
      - run: gh issue edit "$NUMBER" --remove-label "graphql-schema"
        if: ${{ needs.check-changes.outputs.backend == 'false' }}
      
      - run: gh issue edit "$NUMBER" --add-label "ios"
        if: ${{ needs.check-changes.outputs.ios == 'true' }}
      - run: gh issue edit "$NUMBER" --remove-label "ios"
        if: ${{ needs.check-changes.outputs.backend == 'false' }}

      - run: gh issue edit "$NUMBER" --add-label "web"
        if: ${{ needs.check-changes.outputs.web == 'true' }}
      - run: gh issue edit "$NUMBER" --remove-label "web"
        if: ${{ needs.check-changes.outputs.backend == 'false' }}
